@route = elections
@id = D1FA1320-6AA3-42C1-A080-D1D6E0E01043

### GET request to example server
GET localhost:5256/{{route}}/{{id}}/positions

### POST electionPosition
@auth_token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxMTExMTExMS0xMTExLTExMTEtMTExMS0xMTExMTExMTExMTEiLCJlbWFpbCI6ImFkbWluQHN5c3RlbS5jb20iLCJOYXRpb25hbElkIjoiMTAwMDAwMDEiLCJJc0FkbWluIjoidHJ1ZSIsIm5iZiI6MTc0MTQ3NzA2MCwiZXhwIjoxNzQxNDc4ODYwLCJpYXQiOjE3NDE0NzcwNjAsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjUyNTYvIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTI1NiJ9.0lzXPkAKuAlxwEdevIZ8fumIVB-38MTL5hI7lASWey8Wuoi2a3fyV7dtfEkMvvjthXc0ZcDnLB3wCEM6nxoJRA
@position_id = "699CDE80-953E-4331-BBF6-6387678EDED4"
POST localhost:5256/{{route}}/{{id}}/positions
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "PositionId": {{position_id}}
}